[package]
name = "avm1-tree"
version = "0.0.15"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Abstract Syntax Tree (AST) for AVM1"
documentation = "https://github.com/open-flash/avm1-tree"
homepage = "https://github.com/open-flash/avm1-tree"
repository = "https://github.com/open-flash/avm1-tree"
readme = "./README.md"
keywords = ["ast", "swf", "avm1"]
license = "MIT"
edition = "2018"

[lib]
name = "avm1_tree"
path = "src/lib.rs"

[[bin]]
name = "avm1-tree"
path = "src/main.rs"

[dependencies]
hex = "^0.3.2"
serde = "^1.0.89"
serde_derive = "^1.0.89"
serde_json = "^1.0.39"

[dev-dependencies]
test-generator = "^0.2.2"
